[package]
name = "mailparse"
version = "0.4.1"
authors = ["Kartikaya Gupta <kats@seldon.staktrace.com>"]
description = "A simple parser for MIME e-mail messages"
documentation = "https://staktrace.github.io/mailparse/target/doc/mailparse/"
homepage = "https://github.com/staktrace/mailparse/blob/master/README.md"
repository = "https://github.com/staktrace/mailparse"
readme = "README.md"
keywords = ["parser", "email", "rfc822", "mime", "maildir"]
license-file = "LICENSE"

[dependencies]
base64 = "0.1.1"
quoted_printable = "0.3.0"
encoding = "0.2.32"
