[package]
name = "mailparse"
version = "0.5.1"
authors = ["Kartikaya Gupta <kats@seldon.staktrace.com>"]
description = "A simple parser for MIME e-mail messages"
documentation = "https://staktrace.github.io/mailparse/target/doc/mailparse/"
homepage = "https://github.com/staktrace/mailparse/blob/master/README.md"
repository = "https://github.com/staktrace/mailparse"
readme = "README.md"
keywords = ["parser", "email", "rfc822", "mime", "maildir"]
categories = ["email", "parsing"]
license = "0BSD"
exclude = ["target/doc/**"]

[badges]
travis-ci = { repository = "staktrace/mailparse", branch = "master" }

[dependencies]
base64 = "0.1.1"
quoted_printable = "0.3.0"
encoding = "0.2.32"
